import type  { ManifestRow } from "@/types/manifest";

export const mockManifestData: ManifestRow[] = [
  {
    id: 1,
    locationLine1: "214 Maple St",
    locationLine2: "Springfield, IL 62704",
    customer: "Green Valley Apartments",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Completed",
  },
  {
    id: 2,
    locationLine1: "89 Oakwood Ave",
    locationLine2: "Springfield, IL 62703",
    customer: "Oakwood Pizza",
    service: "Extra",
    container: "Front Load",
    size: "4yd",
    status: "Pending",
  },
  {
    id: 3,
    locationLine1: "452 W Elm Dr",
    locationLine2: "Springfield, IL 62703",
    customer: "Bryant Market",
    service: "Scheduled",
    container: "Rear Load",
    size: "6yd",
    status: "Pending",
  },
  {
    id: 4,
    locationLine1: "17 Pinecrest Ln",
    locationLine2: "Springfield, IL 62704",
    customer: "Birchwood Condos",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Pending",
  },
  {
    id: 5,
    locationLine1: "603 S Jefferson St",
    locationLine2: "Springfield, IL 62704",
    customer: "Jefferson St Wine Bar",
    service: "Extra",
    container: "Rear Load",
    size: "8yd",
    status: "Pending",
  },
  {
    id: 6,
    locationLine1: "1280 Riverview Rd",
    locationLine2: "Springfield, IL 62704",
    customer: "Mike’s Pizza",
    service: "Scheduled",
    container: "Front Load",
    size: "8yd",
    status: "Pending",
  },
  {
    id: 7,
    locationLine1: "238 Franklin St",
    locationLine2: "Springfield, IL 62704",
    customer: "Lakeside Manor Condominiums",
    service: "Skipped",
    container: "Front Load",
    size: "4yd",
    status: "Skipped",
  },
  {
    id: 8,
    locationLine1: "742 Sunset Blvd",
    locationLine2: "Springfield, IL 62702",
    customer: "Sunset Retail Plaza",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Pending",
  },
  {
    id: 9,
    locationLine1: "915 Market St",
    locationLine2: "Springfield, IL 62701",
    customer: "Downtown Deli",
    service: "Extra",
    container: "Rear Load",
    size: "4yd",
    status: "Completed",
  },
  {
    id: 10,
    locationLine1: "331 Lincoln Ave",
    locationLine2: "Springfield, IL 62704",
    customer: "Lincoln Office Park",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Pending",
  },
  {
    id: 11,
    locationLine1: "331 Lincoln Ave",
    locationLine2: "Springfield, IL 62704",
    customer: "Lincoln Office Park",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Pending",
  },
  {
    id: 12,
    locationLine1: "331 Lincoln Ave",
    locationLine2: "Springfield, IL 62704",
    customer: "Lincoln Office Park",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Pending",
  },
  {
    id: 13,
    locationLine1: "331 Lincoln Ave",
    locationLine2: "Springfield, IL 62704",
    customer: "Lincoln Office Park",
    service: "Scheduled",
    container: "Front Load",
    size: "6yd",
    status: "Pending",
  },
];