import type { Driver } from "@/types/driver";

export const mockDriver: Driver = {
  id: "driver-1",
  name: "John Doe",
  role: "driver",
  route: {
    route_id: "R-1043",
    service_date: "2026-02-12",
    city: "Springfield",
    state: "IL",
    stops: [
      {
        location_id: 101,
        sequence_order: 1,
        customer_name: "Green Valley Apartments",
        address: "214 Maple St",
        city: "Springfield",
        state: "IL",
        zip: "62704",
        service: "Scheduled",
        container: "6yd",
        status: "PENDING",
        is_extra_pickup: false,
        failure_reason: null,
        proof_of_service_photo: null,
      },
      {
        location_id: 102,
        sequence_order: 2,
        customer_name: "Oakwood Pizza",
        address: "89 Oakwood Ave",
        city: "Springfield",
        state: "IL",
        zip: "62703",
        service: "Extra",
        container: "4yd",
        status: "PENDING",
        is_extra_pickup: true,
        failure_reason: null,
        proof_of_service_photo: null,
      },
      {
        location_id: 103,
        sequence_order: 3,
        customer_name: "Bryant Market",
        address: "452 W Elm Dr",
        city: "Springfield",
        state: "IL",
        zip: "62703",
        service: "Scheduled",
        container: "6yd",
        status: "PENDING",
        is_extra_pickup: false,
        failure_reason: null,
        proof_of_service_photo: null,
      },
      {
        location_id: 104,
        sequence_order: 4,
        customer_name: "Birchwood Condos",
        address: "17 Pinecrest Ln",
        city: "Springfield",
        state: "IL",
        zip: "62704",
        service: "Scheduled",
        container: "6yd",
        status: "PENDING",
        is_extra_pickup: false,
        failure_reason: null,
        proof_of_service_photo: null,
      },
      {
        location_id: 105,
        sequence_order: 5,
        customer_name: "Jefferson St Wine Bar",
        address: "603 S Jefferson St",
        city: "Springfield",
        state: "IL",
        zip: "62704",
        service: "Extra",
        container: "8yd",
        status: "PENDING",
        is_extra_pickup: true,
        failure_reason: null,
        proof_of_service_photo: null,
      },
      {
        location_id: 106,
        sequence_order: 6,
        customer_name: "Mike's Pizza",
        address: "1280 Riverview Rd",
        city: "Springfield",
        state: "IL",
        zip: "62705",
        service: "Scheduled",
        container: "8yd",
        status: "PENDING",
        is_extra_pickup: false,
        failure_reason: null,
        proof_of_service_photo: null,
      },
      {
        location_id: 107,
        sequence_order: 7,
        customer_name: "Lakeside Manor",
        address: "1230 4th St",
        city: "Springfield",
        state: "IL",
        zip: "62705",
        service: "Scheduled",
        container: "6yd",
        status: "PENDING",
        is_extra_pickup: false,
        failure_reason: null,
        proof_of_service_photo: null,
      },
    ],
    health: {
      stops_remaining: 18,
      completed: 2,
      skipped: 6,
      extra_pickups: 8,
    },
  },
};
